---

# `null` will execut all methods
# list of strings will execute selected methods
method_list:
    - pareg_network
    - pareg_network_phi_lm
    - pareg_network_phi_var

term_filter:
    min_size: null
    max_size: null
    sample_num: null

replicate_count: 10

parameters:
    similarityfactor: [0.5]
    ontermcount: [5]
    siggenescaling: ["membercount"]

params_path: config_dispersion_fitting/params.csv
