---

# `null` will execut all methods
# list of strings will execute selected methods
method_list:
    - pareg
    - pareg_network

term_filter:
    min_size: null
    max_size: null
    sample_num: null

replicate_count: 10

parameters:
    similarityfactor: [0.5]
    ontermcount: [5]
    siggenescaling: ["membercount"]

params_path: config_network_regularization/params.csv
