---

# `null` will execut all methods
# list of strings will execute selected methods
method_list:
    - single_term_methods
    - pareg
    - pareg_network
    - pareg_network_10
    - pareg_network_100
    - pareg_network_1000
    - pareg_network_10000
    - mgsa

term_filter:
    min_size: null
    max_size: null
    sample_num: null

replicate_count: 10

parameters:
    similarityfactor: [0.5]
    ontermcount: [5]
    siggenescaling: ["membercount"]

params_path: config_noise/params.csv
