---

# `null` will execut all methods
# list of strings will execute selected methods
method_list:
    - pareg_bernoulli
    - pareg_gaussian
    - pareg_beta
    - pareg_beta_lm
    - pareg_beta_var

term_filter:
    min_size: 50
    max_size: 500
    sample_num: null

replicate_count: 3

parameters:
    similarityfactor: [0.5]
    ontermcount: [20]
    siggenescaling: [0.1]

params_path: config_response_distribution/params.csv
