---

# `null` will execut all methods
# list of strings will execute selected methods
method_list:
    - pareg

term_filter:
    min_size: 50
    max_size: 500
    sample_num: null

replicate_count: 3

parameters:
    similarityfactor: [0.5]
    ontermcount: [5]
    siggenescaling: ["membercount"]

params_path: config_similarity_measures/params.csv
