---

# `null` will execut all methods
# list of strings will execute selected methods
method_list:
    - pareg
    - pareg_clip
    - pareg_ber
    - pareg_gau
    - pareg_network
    - pareg_network_ber
    - pareg_network_gau

term_filter:
    min_size: null
    max_size: null
    sample_num: null

replicate_count: 10

parameters:
    similarityfactor: [0.5]
    ontermcount: [5]
    siggenescaling: ["membercount"]

params_path: config_response_distribution/params.csv
