---

# `null` will execut all methods
# list of strings will execute selected methods
method_list: null

term_filter:
    min_size: null
    max_size: null
    sample_num: null

replicate_count: 100

parameters:
    similarityfactor: [0, 0.25, 0.5, 0.75, 1]
    ontermcount: [1, 5, 10, 50, 100]
    siggenescaling: ["membercount", 0.1, 0.001]
