---

# `null` will execut all methods
# list of strings will execute selected methods
method_list:
    - pareg_noterms
    - pareg_lasso
    - pareg_network
    - pareg_network_lasso

term_filter:
    min_size: 50
    max_size: 500
    sample_num: null

replicate_count: 30

parameters:
    similarityfactor: [0.5]
    ontermcount: [20]
    siggenescaling: [0.1]

params_path: config_ablation_study/params.csv
